import { Campaign, InsightsResponse } from '../types';
import { generateDetailedAiReport } from '../services/gemini';

export const generatePdfReport = async (
    campaigns: Campaign[],
    insightsResponse: InsightsResponse,
    comparisonData: any[]
) => {
    const { jsPDF } = await import('jspdf');
    const doc = new jsPDF();

    const reportText = await generateDetailedAiReport(campaigns, insightsResponse);
    const metrics = insightsResponse.insights;

    const writeWrappedText = (text: string, x: number, y: number, maxWidth: number, lineHeight: number) => {
        const lines = doc.splitTextToSize(text, maxWidth);
        let currentY = y;
        for (let i = 0; i < lines.length; i++) {
            if (currentY > 275) {
                doc.addPage();
                currentY = 20;
            }
            doc.text(lines[i], x, currentY);
            currentY += lineHeight;
        }
        return currentY;
    };

    doc.setFillColor(31, 41, 55);
    doc.rect(0, 0, 210, 40, 'F');
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(255, 255, 255);
    doc.text("STRATEGIC AD PERFORMANCE REPORT", 20, 25);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`GENERATED BY MIXO AI ENGINE  |  FULL 14-CAMPAIGN POOL AUDIT  |  ${new Date().toLocaleDateString()}`, 20, 34);

    doc.setFillColor(248, 250, 252);
    doc.roundedRect(15, 50, 180, 45, 3, 3, 'F');
    doc.setTextColor(71, 85, 105);
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.text("TOTAL AD INVESTMENT", 25, 62);
    doc.text("CONVERSIONS ACQUIRED", 85, 62);
    doc.text("AVERAGE COST/CLICK", 145, 62);
    doc.setTextColor(30, 41, 59);
    doc.setFontSize(18);
    doc.text(`$${metrics.total_spend.toLocaleString()}`, 25, 75);
    doc.text(`${metrics.total_conversions.toLocaleString()}`, 85, 75);
    doc.text(`$${metrics.avg_cpc.toFixed(2)}`, 145, 75);

    doc.setTextColor(17, 24, 39);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("1. Executive Strategic Insights", 20, 110);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(55, 65, 81);
    const cleanText = reportText.replace(/\*\*/g, '').replace(/###/g, '').replace(/#/g, '');
    let nextY = writeWrappedText(cleanText, 20, 120, 170, 6);

    if (nextY > 180) {
        doc.addPage();
        nextY = 25;
    } else {
        nextY += 20;
    }

    doc.setTextColor(17, 24, 39);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("2. Performance Benchmark: 14-Campaign Audit", 20, nextY);

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(107, 114, 128);
    nextY += 8;
    doc.text("Comprehensive comparative analysis sorted by conversion efficiency (ROI Rank)", 20, nextY);

    nextY += 12;
    doc.setFillColor(241, 245, 249);
    doc.rect(20, nextY, 170, 8, 'F');
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(51, 65, 85);
    doc.text("RANK", 22, nextY + 5.5);
    doc.text("CAMPAIGN NAME", 35, nextY + 5.5);
    doc.text("INVESTMENT", 95, nextY + 5.5);
    doc.text("RETURNS", 125, nextY + 5.5);
    doc.text("ROI SCORE", 155, nextY + 5.5);
    nextY += 12;

    comparisonData.slice(0, 14).forEach((item, idx) => {
        if (nextY > 275) {
            doc.addPage();
            nextY = 25;
        }

        doc.setFontSize(8);
        doc.setFont("helvetica", idx < 3 ? "bold" : "normal");
        doc.setTextColor(31, 41, 55);

        doc.text(`${idx + 1}`, 22, nextY);
        doc.text(item.name.length > 28 ? item.name.substring(0, 25) + "..." : item.name, 35, nextY);
        doc.text(`$${item.spend.toLocaleString()}`, 95, nextY);
        doc.text(`${item.conversions.toLocaleString()}`, 125, nextY);

        if (item.roi > 2.0) doc.setTextColor(5, 150, 105);
        else doc.setTextColor(31, 41, 55);

        doc.text(`${item.roi.toFixed(3)}x`, 155, nextY);

        doc.setDrawColor(241, 245, 249);
        doc.line(20, nextY + 2, 190, nextY + 2);

        nextY += 10;
    });

    doc.save(`MixoAds_Full_Strategic_Audit.pdf`);
};
